// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf8HFY_aWlZs7L4884C72_NaCeQ3F0drc',
    appId: '1:650581131380:web:40d273a1bd967f219dd121',
    messagingSenderId: '650581131380',
    projectId: 'my-notes-flutter-project-ebbe4',
    authDomain: 'my-notes-flutter-project-ebbe4.firebaseapp.com',
    storageBucket: 'my-notes-flutter-project-ebbe4.appspot.com',
    measurementId: 'G-SY8NBW7RSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCF3llfENw0FuYvEhjkqqmqyk3IQvne8',
    appId: '1:650581131380:android:956265d9c504c1f69dd121',
    messagingSenderId: '650581131380',
    projectId: 'my-notes-flutter-project-ebbe4',
    storageBucket: 'my-notes-flutter-project-ebbe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2X3JgyOydDRdoLPooAwGi9Ndb4T0Jy9o',
    appId: '1:650581131380:ios:8a60d64642eee7ab9dd121',
    messagingSenderId: '650581131380',
    projectId: 'my-notes-flutter-project-ebbe4',
    storageBucket: 'my-notes-flutter-project-ebbe4.appspot.com',
    iosClientId: '650581131380-t0e6fhrde5d55kdvlqdm4l6rj4i8bosg.apps.googleusercontent.com',
    iosBundleId: 'com.nexuslabs.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2X3JgyOydDRdoLPooAwGi9Ndb4T0Jy9o',
    appId: '1:650581131380:ios:8a60d64642eee7ab9dd121',
    messagingSenderId: '650581131380',
    projectId: 'my-notes-flutter-project-ebbe4',
    storageBucket: 'my-notes-flutter-project-ebbe4.appspot.com',
    iosClientId: '650581131380-t0e6fhrde5d55kdvlqdm4l6rj4i8bosg.apps.googleusercontent.com',
    iosBundleId: 'com.nexuslabs.mynotes',
  );
}
